# This workflow copies the docs subfolder from another repo into the docs/reponame subfolder of this repo

name: justinwritescode docs cd
description: This workflow copies the docs subfolder from another repo into the docs/reponame subfolder of this repo

inputs:
  repository_name:
    required: true
    description: The name of the repository to copy the docs from
  github_token:
    required: true
    description: The GitHub token to use to access the repository
   
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: "composite"
    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    - name: Clone the docs repo
      env:
        REPOSITORY_NAME: ${{ inputs.repository_name }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: | 
        cd "$GITHUB_WORKSPACE"
        git config --global user.email "docs-cd@justinwritescode.com"
        git config --global user.name "docs cd"
        export repo_name="$(echo \"$REPOSITORY_NAME\"|cut -d "/" -f 2)";
        echo "Target repo owner/name: $REPOSITORY_NAME"
        echo "Cloning the docs repo into $GITHUB_WORKSPACE/docs...";
        git clone "https://github.com/justinwritescode/docs.git" docs;
      shell: bash
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
    - name: Clone the target repo
      env:
        REPOSITORY_NAME: ${{ inputs.repository_name }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Target repo name: $repo_name";
        echo "Cloning the target repo into $GITHUB_WORKSPACE/$repo_name..."
        cd "$GITHUB_WORKSPACE";
        /usr/bin/git clone --single-branch --branch main "https://github.com/justinwritescode/$repo_name" $repo_name; 
      shell: bash
    - name: Copy the target repo into the docs repo
      env:
        REPOSITORY_NAME: ${{ inputs.repository_name }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        rm -rf "$GITHUB_WORKSPACE/docs/$repo_name";
        mkdir -p "$GITHUB_WORKSPACE/docs/$repo_name";
        cp -R "$GITHUB_WORKSPACE/$repo_name/docs" "$GITHUB_WORKSPACE/docs/$repo_name";
        cd "$GITHUB_WORKSPACE/docs/$repo_name"
        /usr/bin/git add .
        /usr/bin/git commit -m "Docs CD Deployment of ${{github.event.inputs.repository_name}} repo"
        /usr/bin/git push -u origin HEAD:main
      shell: bash
