# This workflow copies the docs subfolder from another repo into the docs/reponame subfolder of this repo

name: justinwritescode docs cd
description: This workflow copies the docs subfolder from another repo into the docs/reponame subfolder of this repo

inputs:
  repository_name:
    required: true
    description: The name of the repository to copy the docs from
  github_token:
    required: true
    description: The GitHub token to use to access the repository
   
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: "composite"
    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        repository: justinwritescode/docs
        token: ${{github.event.inputs.github_token}}
    - run: |
        git config --global user.email "docs-cd@justinwritescode.com"
        git config --global user.name "docs cd"
        repo_name="$(echo \"${{github.event.inputs.repository_name}}\"|cut -d "/" -f 2)";
        echo "Target repo owner/name: ${{github.event.inputs.repository_name}}"
        echo "Target repo name: $repo_name";
        echo "Cloning the target repo..."
        cd "/home/runner/work";
        /usr/bin/git clone --single-branch --branch main "https://github.com/justinwritescode/$repo_name"
        rm -rf "/home/runner/work/docs/docs/$repo_name";
        cp -R "/home/runner/work/$repo_name/docs" "/home/runner/work/docs/docs/$repo_name"
        cd /home/runner/work/docs/docs/$repo_name
        /usr/bin/git add .
        /usr/bin/git commit -m "Docs CD Deployment of ${{github.event.inputs.repository_name}} repo"
        /usr/bin/git push -u origin HEAD:main
      shell: bash
      
